# Nome del workflow
name: Build and Deploy

# Trigger: esegue il workflow a ogni push sul branch main
on:
  push:
    branches: [ "main" ]

jobs:
  # Nome del job
  build:
    # Usa una macchina Ubuntu di GitHub Actions
    runs-on: ubuntu-latest

    steps:
    # Checkout del repository per accedere ai file
    - uses: actions/checkout@v4

    # Compila l'app .NET e genera la cartella publish
    - name: Build .NET app
      run: dotnet publish ./app -c Release -o publish

    # Connessione SSH alla macchina locale per fare il deploy
    - name: Deploy to local machine via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        # Indirizzo IP o hostname della macchina locale
        host: ${{ secrets.SSH_HOST }}
        # Utente SSH configurato nei secrets
        username: ${{ secrets.SSH_USER }}
        # Chiave privata SSH
        key: ${{ secrets.SSH_KEY }}
        # Script eseguito da GitHub Actions sulla macchina locale
        script: |

          # Copia i file compilati dentro il container esistente
          docker cp publish/. mydevops_container:/app
          # Riavvia il processo dotnet dentro il container (senza ricrearlo)
          docker exec mydevops_container pkill dotnet || true